### ISSUE TITLE
2023 Ready?

### ISSUE THREAD

**Issue by cormo1990** [jumping2000/elettrodomestici#1]
Ciao Giampi, come sempre grazie del preziosissimo lavoro.
ho provato a scaricare il pacchetto 2023 ma sembra che manchino un po' di file giusto?
quando pensi di riuscire a rilasciarlo? sembra davvero strepitoso

grazie mille!

**Comment by jumping2000** [comment]
Ciao, sei sul gruppo TElegram di hassio help https://t.me/HassioHelp ? conto in questi giorni di rilasciare il primo package, scriverò su Telegram per i test, purtroppo il package ha raggiunto un tale livello di completezza che riuscire a rilasciare una versione che tenga conto di tutti i possibili errori/differenze è complicato
